### ISSUE TITLE
Roy 

### ISSUE THREAD

**Issue by 1234742** [HMCL-dev/HMCL-PE#217]
**Describe the bug**

**To Reproduce**

**Paste logs here**

<details>
<summary>log file name</summary>

```
<---------paste log here, and delete this line
```
</details>

<details>
<summary>another log file name</summary>

```
<---------paste log here, and delete this line
```
</details>

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: [e.g. HUAWEI Mate 50]
 - OS: [e.g. Android 10]

**Additional context**

**Comment by kjjjjjjjjjjjj** [comment]
I not give you

**Comment by kjjjjjjjjjjjj** [comment]
I do my best for you
