### ISSUE TITLE
Whats the Difference between Boat, Pojavlauncher?

### ISSUE THREAD

**Issue by TGEBkebu** [HMCL-dev/HMCL-PE#218]
Whats the difference between Boat Launcher and the Pojavlauncher in the Global Game Settings? Also, this launcher better than Pojavlauncher :>

**Comment by Username10926663** [comment]
Boat: Used by **Boardwalk** back then, is a improved kernel giving you more fps.
PojavLauncher: Using **Java** this kernel is designed to run Minecraft,  not giving more fps.
