### ISSUE TITLE
Return

### ISSUE THREAD

**Issue by Venvvs** [HMCL-dev/HMCL-PE#222]
Is this project dead or is it coming back?
Would be nice to see a return as the app itself isn't working properly now on my s23 ultra and would love to get dawncraft going on android and it seems your mod installer was the best so far 😂

**Comment by WesleyVanNeck** [comment]
> Is this project dead or is it coming back? Would be nice to see a return as the app itself isn't working properly now on my s23 ultra and would love to get dawncraft going on android and it seems your mod installer was the best so far 😂

use https://github.com/FCL-Team/FoldCraftLauncher
