### ISSUE TITLE
Can't play longer

### ISSUE THREAD

**Issue by MinecraftJavafan9383** [HMCL-dev/HMCL-PE#224]
I can't play any longer in luncher.when I play the game then start quit and return to main screen.Please fix it as soon as possible.My Phone is Vivo Y17S .Ram6 128.After the device update that quiting happen. If you fix I will love to play.

**Comment by kjjjjjjjjjjjj** [comment]
No one response you I love to play hmcl but no one responsing me and you we need to start up project about hmcl I have a message for everyone to start a project like hmcl we need updates I love to play to
