### ISSUE TITLE
1.21版本需要JAVA21

### ISSUE THREAD

**Issue by 6833321** [HMCL-dev/HMCL-PE#231]
1.21发布测试版了,我们却没有JAVA21。以后Minecraft或许需要更高的Java版本，我们需要一个方法来通过Minecraft的需要自动下载对应Java。

**Comment by zkitefly** [comment]
3.5.8 已支持下载 Java 21，确定是使用该版本测试的吗

**Comment by 6833321** [comment]
不确定

**Comment by zkitefly** [comment]
哦，没看见是 HMCL-PE（
HMCL-PE 已停止更新，建议使用 FCL 启动器
