### ISSUE TITLE
Can I join with available so I can give the update

### ISSUE THREAD

**Issue by kjjjjjjjjjjjj** [HMCL-dev/HMCL-PE#235]
Hello how are you 
Developers I am Kjjjjjjjjjjjj
Kindly can I join this reproductory so I can give the updates of HMCL-pe 😊 
I love this launcher and most of the people love this launcher so please give us an opportunity to update this launcher kindly please help us help me for my this task

**Comment by nsgamer442** [comment]
🙂

**Comment by kjjjjjjjjjjjj** [comment]
Oh my dear sister did you adding me in this repository hmmmmmmmmm
