### ISSUE TITLE
Activate pointer even when i am in the game (server, world, ect..) 

### ISSUE THREAD

**Issue by duynamDJ** [HMCL-dev/HMCL-PE#46]
Hello, i would like to know if there is a way to some how activate the cursor even when i am in the game (not the menu)
If this is not added yet, then please add it.
Reason why is that i am using replay mod, the problem is that i cant touch the buttons displayed on the screen. The buttons i am mention is from the picture.
So if you can, tell me how to activate cursor ingame, or atleast if it not in the launcher yet, please add the feauture. 
![images (28)~2](https://user-images.githubusercontent.com/82700366/189506870-49189780-495e-4492-9cf9-f3e090339e7d.jpeg)

**Comment by lehoanduphong** [comment]
> Hello, i would like to know if there is a way to some how activate the cursor even when i am in the game (not the menu) If this is not added yet, then please add it. Reason why is that i am using replay mod, the problem is that i cant touch the buttons displayed on the screen. The buttons i am mention is from the picture. So if you can, tell me how to activate cursor ingame, or atleast if it not in the launcher yet, please add the feauture. ![images (28)~2](https://user-images.githubusercontent.com/82700366/189506870-49189780-495e-4492-9cf9-f3e090339e7d.jpeg)

Use the "T" key to show the mouse pointer
