### ISSUE TITLE
Not working on Android 6

### ISSUE THREAD

**Issue by GTG921** [HMCL-dev/HMCL-PE#53]
**Describe the bug**

**To Reproduce**

**Paste logs here**

<details>
<summary>log file name</summary>

```
<---------paste log here, and delete this line
```
</details>

<details>
<summary>another log file name</summary>

```
<---------paste log here, and delete this line
```
</details>

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: [e.g. HUAWEI Mate 50]
 - OS: [e.g. Android 10]

**Additional context**

**Comment by LegacyGamerHD** [comment]
known you need android 8.1 or higer rn

**Comment by GTG921** [comment]
Hi sir I request you to make hmcl-pe to Android 4.0 to 7.0
Then this launcher is best than other launchers
