### ISSUE TITLE
Download Modpacks

### ISSUE THREAD

**Issue by GabeNewID** [HMCL-dev/HMCL-PE#88]
How do I download modpacks?

Whenever I select the file to download, the "install" button doesn't work.

![16647078403253453231411461131696](https://user-images.githubusercontent.com/114858754/193450324-826ddca4-5ada-4a40-beee-edbf178368a5.jpg)

I couldn't find any tutorial anywhere on how to install modpacks directly from the app, so I turned to github.

**Comment by LegacyGamerHD** [comment]
known issue
